### ISSUE TITLE
suggestion: rename kobopatch.yaml to kobopatch-example.yaml in releases?

### ISSUE THREAD

**Issue by taosxx** [geek1011/kobopatch#15]
Having the option to use a global kobopatch.yaml (with overrides for the usually applied patches) over several releases is - at least for me - one of the biggest advantages of kobopatch over the old patch32lsb approach to patching. As long as  a patch is still available for a later firmware version, patching is just a mouse-click away without having to go through several patch files and manually changing 'no' to 'yes'.

Would it make sense to rename the kobopatch.yaml file in the release zip files to something like kobopatch-template/example/default.yaml to:
1. make it clear that the customized kobopatch.yaml can be re-applied for patching a newer firmware version
2. prevent the customized kobopatch.yaml from being accidentally overwritten by updating kobopatcher

**Comment by geek1011** [comment]
I don't think I will do this, as the current method works well, and is easy to implement and use.
