### ISSUE TITLE
Add possibility to include other "package" in KoboRoot.tgz

### ISSUE THREAD

**Issue by memiks** [geek1011/kobopatch#16]
Hello,

It may be good to have possibility to merge other KoboRoot.tgz packages in the output one.
for example :
* add a packages folder on the same level than src
* put all packages tgz in this folder (for exemple kfmon.tgz, nightmode.tgz, ...)
* list in kobopatch.yaml packages names
* kobopatch will merge packages in order of the list.

kobopatch.yaml example:
>overrides:
>  src/nickel.yaml:
>merges:
> packages/kfmon.tgz
> packages/nightmode.tgz

**Comment by geek1011** [comment]
This has been [discussed](https://www.mobileread.com/forums/showthread.php?p=3720374) on MobileRead, and the conclusion was that it was a lot simpler to do it using external tools (like the `--concatenate` option of tar). The reason behind that it would add too much complexity to kobopatch to handle conflicts, duplicates, file permissions, etc when merging the tar archives.
