### ISSUE TITLE
Support loading extra yaml config files

### ISSUE THREAD

**Issue by norbusan** [geek1011/kobopatch#8]
Hi Patrick,
thanks for the many updates and the added files section, I am adding a few issues of feature requests that might be useful.

The first is about loading additional yaml files. ATM we need to copy the overrides section, and the files section for each release. It would be nice if one could say
```
kobopatch -c ../overrides.yaml -c ../files.yaml
```
to *add* two yaml files. They can contain whatever yaml code there is, and it is merged into the main configuration overriding previously set values if already set.

If this is too complicated, loading automatically without command line args only one additional config file like `../local.yaml` would be an option, too. It would be in .. to be outside the current directory and can be reused for new versions.

Thanks for consideration

**Comment by norbusan** [comment]
I am reconsidering my idea. Merging yamls is not trivial in generality, so maybe there is a better approach: Can you comment out the `overrides` section in the included .yaml? In this case I could do
`cat ../overrides.yaml >> kobopatch.yaml` and similar for the files section.

At the moment this would give
```
Fatal: Could not parse kobopatch.yaml: yaml: unmarshal errors:
  line 48: key "src/nickel.yaml" already set in map
  line 59: key "src/libadobe.so.yaml" already set in map
  line 61: key "src/libnickel.so.1.0.0.yaml" already set in map
  line 65: key "src/librmsdk.so.1.0.0.yaml" already set in map
```
Since the section is anyway empty, I guess it shouldn't be a problem ;-)

Best

**Comment by geek1011** [comment]
It's true that merging YAMLs is not trivial. What you could do is to split it at the first empty line after the log setting), and the first bit is version specific, and you can append the other half from your config.

If you want, I could store the version in a separate file so kobopatch.yaml does not change between versions.

**Comment by norbusan** [comment]
Well, I don't want to ask anything just for my convenience. If you think this approach makes sense, please go ahead.

I agree that having static and changing content separated is a good idea in any case.

In the same vein, I always recommend not to have hard-coded information in the source, like the file name and location of the config file. What about "if an argument is passed on the command line, and it is a file, use this one as kobopatch.yaml, if the value at the command line is a literal -, read the config from stdin, and if nothing is passed on the command line, use the current behaviour". This way there are many easy ways to pluck things together on the fly.

**Comment by norbusan** [comment]
I added a pull request concerning the config file reading mechanism. Be reminded that this is my first go code ever ;-)

**Comment by geek1011** [comment]
@norbusan Thanks for the pull request! I've actually been meaning to add support for this for a while, but never got around to it.
