### ISSUE TITLE
Support including whole directories

### ISSUE THREAD

**Issue by norbusan** [geek1011/kobopatch#9]
The files feature is nice, but it would be even better if we could include everything below a directory, too. Something like
```
  /path/to/foobar/: mnt/onboard/fonts/
```
would copy everything from the directory `foobar/` into the fonts directory.

Thanks for you consideration.

**Comment by geek1011** [comment]
I've been thinking about this, and have decided it's best (at least for now) not to implement this feature. The biggest issue is that firstly, it's quite easy to make a mistake and copy more or less than expected. Secondly, users may become confused by the treatment of trailing slashes. I could treat them like rsync (trailing slash copies contents, no slash copies the dir itself), but that adds a lot of complexity to the code and confusion for users.

Thanks for the suggestion!

**Comment by norbusan** [comment]
Ok, thanks for your explanation!

**Comment by geek1011** [comment]
No problem!
